version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=https://supermarket-back.pro
    ports:
      - "80:80"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    network_mode: "host"
