version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_URL: https://supermarket-back.pro
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    network_mode: "host"
